### PR TITLE
Add closing Messages after tapback

### PR DESCRIPTION
**Pull request by jandamm**
Except when messages was the front application when running the workflow.

If the user has overwritten Command Tab with something else it might not work.
Ideally we would have an action which activates the previous app instead of relying on Command Tab.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please provide the packaged workflow with your changes. Not as part of the PR, but just attach it here so I can get a better high level sense of what you’re pursuing.

**Comment by vitorgalvao** [comment]
Thank you for the submission, but after a review and rewrite I’ll pass on it.

The commit message doesn’t accurately describe what’s going on, as you’re going back to the previous app, not closing Messages. Aesthetically, that branching for the frontmost app clashes with the rest of the workflow, but that doesn’t matter much as it’s easily fixable. Technically you don’t need <kbd>⌘</kbd><kbd>⇥</kbd> (and in fact should actively avoid it; GUI automation should be kept to the bare minimum) nor checking if the app is the same or not. All you need is to reopen whatever app was frontmost at the time; doesn’t matter if it already was Messages because if it was you’ll just stay where you were.

[Like so.](https://github.com/user-attachments/files/17445681/Tapback.Message.alfredworkflow.zip)

You’re welcome to use that or your own version, but no guarantees yet that I’ll release those changes. I may reconsider but am currently inclined to not release it, as I’m testing it and find it a positive that one stays in Messages after the reaction. I’ll pay attention if more people want this (so far you’re the only one who mentioned it).

Have a nice weekend.

**Comment by jandamm** [comment]
Thanks for your feedback. I got the idea of opening the previous app after creating the PR.
With a short delay before switching to the previous app it works as expected.

Would you be open to add it as a configuration option? Something like this:
CleanShot 2024-10-22 at 09 28 46@2x

**Comment by jandamm** [comment]
Thinking about it some more it might be the best idea to add a Cmd+Enter mapping which sends Messages into the background.
No configuration needed and one can decide on execution whether to open messages or stay in context.

**Pull request closed without merging**
